### ISSUE TITLE
Action fails if user is a bot

### ISSUE THREAD

**Issue by lkiesow** [TheModdingInquisition/actions-team-membership#3]
Given the documentation and a configuration like this, I would expect the action to always succeed unless GitHub's API is down:

```yaml
- uses: TheModdingInquisition/actions-team-membership@v1.0
  with:
    team: 'my-team'
    token: ******
    exit: false
```

But if the user to check is no regular user but a bot, the action fails completely:

```
Error: Error while trying to establish team membership:
GraphqlResponseError: Request failed due to following response errors:
 - Could not resolve to a User with the login of 'dependabot[bot]'.
```

Since `dependabot[bot]` is not a team member of the team to check, and `exit: false` is configured, I would expect the action to succeed and have the output `permitted` set to `false`.
